# Generated by Django 6.0.3 on 2026-03-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('subscription_status', models.CharField(default='trial', max_length=20)),
                ('had_trial_before', models.BooleanField(default=False)),
                ('trial_end_date', models.DateTimeField(blank=True, null=True)),
                ('subscription_expiry', models.DateTimeField(blank=True, null=True)),
                ('is_unlimited_usage', models.BooleanField(default=False)),
                ('is_onboarded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('type', models.CharField(choices=[('MAIN', 'Main'), ('SUB', 'Sub')], default='SUB', max_length=10)),
                ('access_password', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BranchSettings',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('logo', models.URLField(blank=True, max_length=500, null=True)),
                ('signature_image', models.URLField(blank=True, max_length=500, null=True)),
                ('enable_signature', models.BooleanField(default=False)),
                ('business_name', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('currency', models.CharField(default='UGX', max_length=10)),
                ('needs_onboarding', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('yearly_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('max_users', models.IntegerField(default=5)),
                ('unlimited_users', models.BooleanField(default=False)),
                ('max_sales_per_month', models.IntegerField(default=100)),
                ('unlimited_sales', models.BooleanField(default=False)),
                ('max_products', models.IntegerField(default=50)),
                ('unlimited_products', models.BooleanField(default=False)),
                ('max_locations', models.IntegerField(default=1)),
                ('unlimited_locations', models.BooleanField(default=False)),
                ('max_customers', models.IntegerField(default=100)),
                ('unlimited_customers', models.BooleanField(default=False)),
                ('has_free_trial', models.BooleanField(default=False)),
                ('trial_days', models.IntegerField(default=14)),
                ('features', models.JSONField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
