# Generated by Django 6.0.3 on 2026-03-18 22:48

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_activityhistory_subscriptiontransaction_task_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityhistory',
            options={'verbose_name_plural': 'Activity Histories'},
        ),
        migrations.AlterModelOptions(
            name='agency',
            options={'verbose_name_plural': 'Agencies'},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='branchcounter',
            options={'verbose_name_plural': 'Branch Counters'},
        ),
        migrations.AlterModelOptions(
            name='branchsettings',
            options={'verbose_name_plural': 'Branch Settings'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'verbose_name_plural': 'Packages'},
        ),
        migrations.AlterModelOptions(
            name='subscriptiontransaction',
            options={'verbose_name_plural': 'Subscription Transactions'},
        ),
        migrations.AlterModelOptions(
            name='systemconfig',
            options={'verbose_name_plural': 'System Configs'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterModelOptions(
            name='taskcategory',
            options={'verbose_name_plural': 'Task Categories'},
        ),
        migrations.AlterField(
            model_name='activityhistory',
            name='id',
            field=models.CharField(default=core.utils.gen_ah_id, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='agency',
            name='id',
            field=models.CharField(default=core.utils.gen_ag_id, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='branch',
            name='id',
            field=models.CharField(default=core.utils.gen_br_id, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='branchcounter',
            name='id',
            field=models.CharField(default=core.utils.gen_bc_id, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='branchsettings',
            name='id',
            field=models.CharField(default=core.utils.gen_bs_id, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='package',
            name='id',
            field=models.CharField(default=core.utils.gen_pa_id, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subscriptiontransaction',
            name='id',
            field=models.CharField(default=core.utils.gen_st_id, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='id',
            field=models.CharField(default=core.utils.gen_sc_id, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.CharField(default=core.utils.gen_ta_id, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taskcategory',
            name='id',
            field=models.CharField(default=core.utils.gen_tc_id, max_length=30, primary_key=True, serialize=False),
        ),
    ]
