# Generated by Django 6.0.3 on 2026-03-19 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_alter_activityhistory_options_alter_agency_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityhistory',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='activityhistory',
            name='profile_id',
        ),
        migrations.RemoveField(
            model_name='activityhistory',
            name='profile_name',
        ),
        migrations.AddField(
            model_name='activityhistory',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='core_app.agency'),
        ),
        migrations.AddField(
            model_name='activityhistory',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='core_app.branch'),
        ),
        migrations.AlterField(
            model_name='activityhistory',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='subscription_status',
            field=models.CharField(default='expired', max_length=20),
        ),
        migrations.AlterField(
            model_name='branch',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_branches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='branch',
            name='location',
            field=models.CharField(default='Default Location', max_length=200),
        ),
        migrations.AlterField(
            model_name='branchsettings',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='features',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiontransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='subscriptiontransaction',
            name='billing_cycle',
            field=models.CharField(default='monthly', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='value',
            field=models.JSONField(default=dict),
        ),
    ]
