# Generated by Django 6.0.3 on 2026-04-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_remove_activityhistory_location_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='subscription_status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='expired', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptiontransaction',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscriptiontransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
    ]
