# Generated by Django 6.0.3 on 2026-04-14 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_alter_agency_subscription_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyRoleDirectory',
            fields=[
            ],
            options={
                'verbose_name': 'Agency Role Directory',
                'verbose_name_plural': 'Roles by Agency',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core_app.agency',),
        ),
    ]
