# Generated by Django 6.0.3 on 2026-04-16 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_agencyroledirectory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskcategory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='taskcategory',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='taskcategory',
            name='user',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskCategory',
        ),
    ]
