# Generated by Django 6.0.3 on 2026-04-16 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0008_alter_taskcategory_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityHistory',
        ),
    ]
