# Generated by Django 6.0.3 on 2026-04-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0009_delete_activityhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='is_frozen',
            field=models.BooleanField(default=False, help_text='If true, all users in this agency are blocked from system access.'),
        ),
        migrations.AddField(
            model_name='branchcounter',
            name='last_reset_month',
            field=models.IntegerField(default=0),
        ),
    ]
