# Generated by Django 6.0.3 on 2026-04-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityhistory',
            name='profile_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='activityhistory',
            name='profile_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
