# Generated by Django 6.0.3 on 2026-04-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activityhistory_profile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityhistory',
            name='activity_type',
            field=models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='activityhistory',
            name='module',
            field=models.CharField(choices=[('SALES', 'Sales'), ('INVENTORY', 'Inventory'), ('EXPENSES', 'Expenses'), ('FINANCE', 'Finance'), ('CUSTOMERS', 'Customers'), ('TASKS', 'Tasks')], db_index=True, max_length=100),
        ),
    ]
