# Generated by Django 6.0.3 on 2026-03-18 22:48

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='customercategory',
            options={'verbose_name_plural': 'Customer Categories'},
        ),
        migrations.AlterModelOptions(
            name='favoritecustomer',
            options={'verbose_name_plural': 'Favorite Customers'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(default=core.utils.gen_cu_id, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customercategory',
            name='id',
            field=models.CharField(default=core.utils.gen_cc_id, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='favoritecustomer',
            name='id',
            field=models.CharField(default=core.utils.gen_fc_id, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.CharField(default=core.utils.gen_tk_id, max_length=30, primary_key=True, serialize=False),
        ),
    ]
