# Generated by Django 6.0.3 on 2026-04-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_order_count_customer_total_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='order_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_spent',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
