# Generated by Django 6.0.3 on 2026-03-16 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_activityhistory_subscriptiontransaction_task_and_more'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarriageInward',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carriage_inwards', to='core_app.branch')),
                ('cash_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.cashaccount')),
                ('cash_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.cashtransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carriage_inwards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
