# Generated by Django 6.0.3 on 2026-03-18 22:48

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_carriageinward'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carriageinward',
            options={'verbose_name_plural': 'Carriage Inwards'},
        ),
        migrations.AlterModelOptions(
            name='cashaccount',
            options={'verbose_name_plural': 'Cash Accounts'},
        ),
        migrations.AlterModelOptions(
            name='cashtransaction',
            options={'verbose_name_plural': 'Cash Transactions'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'verbose_name_plural': 'Expense Categories'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterField(
            model_name='carriageinward',
            name='id',
            field=models.CharField(default=core.utils.gen_ci_id, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cashaccount',
            name='id',
            field=models.CharField(default=core.utils.gen_ac_id, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='id',
            field=models.CharField(default=core.utils.gen_ct_id, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='id',
            field=models.CharField(default=core.utils.gen_ex_id, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='id',
            field=models.CharField(default=core.utils.gen_ec_id, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.CharField(default=core.utils.gen_tx_id, max_length=30, primary_key=True, serialize=False),
        ),
    ]
