# Generated by Django 6.0.3 on 2026-03-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_remove_transaction_agency_id_carriageinward_agency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='reference_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
