# Generated by Django 6.0.3 on 2026-04-16 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_cashtransaction_reference_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='person_in_charge',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
