# Generated by Django 6.0.3 on 2026-04-16 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_expense_person_in_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='expense',
            name='person_in_charge',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
