# Generated by Django 6.0.3 on 2026-04-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_expense_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='credits_amount',
            field=models.IntegerField(default=0),
        ),
    ]
