# Generated by Django 6.0.3 on 2026-03-16 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarriageInward',
        ),
    ]
