# Generated by Django 6.0.3 on 2026-03-18 22:48

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_delete_carriageinward'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='producthistory',
            options={'verbose_name_plural': 'Product Histories'},
        ),
        migrations.AlterModelOptions(
            name='requisition',
            options={'verbose_name_plural': 'Requisitions'},
        ),
        migrations.AlterModelOptions(
            name='requisitionitem',
            options={'verbose_name_plural': 'Requisition Items'},
        ),
        migrations.AlterModelOptions(
            name='stockaudit',
            options={'verbose_name_plural': 'Stock Audits'},
        ),
        migrations.AlterModelOptions(
            name='stockaudititem',
            options={'verbose_name_plural': 'Stock Audit Items'},
        ),
        migrations.AlterModelOptions(
            name='stocktransfer',
            options={'verbose_name_plural': 'Stock Transfers'},
        ),
        migrations.AlterModelOptions(
            name='stocktransferitem',
            options={'verbose_name_plural': 'Stock Transfer Items'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name_plural': 'Suppliers'},
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(default=core.utils.gen_ca_id, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(default=core.utils.gen_pr_id, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='id',
            field=models.CharField(default=core.utils.gen_ph_id, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='id',
            field=models.CharField(default=core.utils.gen_re_id, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='requisitionitem',
            name='id',
            field=models.CharField(default=core.utils.gen_ri_id, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stockaudit',
            name='id',
            field=models.CharField(default=core.utils.gen_au_id, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stockaudititem',
            name='id',
            field=models.CharField(default=core.utils.gen_ai_id, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='id',
            field=models.CharField(default=core.utils.gen_tr_id, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stocktransferitem',
            name='id',
            field=models.CharField(default=core.utils.gen_ti_id, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='id',
            field=models.CharField(default=core.utils.gen_su_id, max_length=30, primary_key=True, serialize=False),
        ),
    ]
