# Generated by Django 6.0.3 on 2026-03-19 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_remove_activityhistory_location_id_and_more'),
        ('inventory', '0003_alter_category_options_alter_product_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producthistory',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='stockaudit',
            name='location',
        ),
        migrations.RemoveField(
            model_name='stocktransferitem',
            name='product_id',
        ),
        migrations.AddField(
            model_name='producthistory',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_histories', to='core_app.agency'),
        ),
        migrations.AddField(
            model_name='producthistory',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_histories', to='core_app.branch'),
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisition_items', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='stockaudit',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_audits', to='core_app.agency'),
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_items', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='new_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='new_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='new_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='old_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='old_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisitions', to='core_app.branch'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requisitionitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockaudit',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_audits', to='core_app.branch'),
        ),
        migrations.AlterField(
            model_name='stockaudititem',
            name='counted_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockaudititem',
            name='expected_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockaudititem',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='stockaudititem',
            name='variance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='from_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_transfers', to='core_app.branch'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='to_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_transfers', to='core_app.branch'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stocktransferitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
