# Generated by Django 6.0.3 on 2026-03-27 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_producthistory_location_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
