# Generated by Django 6.0.3 on 2026-04-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionitem',
            name='urgent_item',
            field=models.BooleanField(default=False),
        ),
    ]
