# Generated by Django 6.0.3 on 2026-04-14 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_agencyroledirectory'),
        ('inventory', '0006_requisitionitem_urgent_item'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('agency', 'name')},
        ),
        migrations.RemoveField(
            model_name='category',
            name='branch',
        ),
    ]
