# Generated by Django 6.0.3 on 2026-04-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_category_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthistory',
            name='type',
            field=models.CharField(choices=[('SALE', 'Sale'), ('RETURN_IN', 'Return In'), ('RESTOCK', 'Restock'), ('ADJUSTMENT', 'Adjustment'), ('PRICE_CHANGE', 'Price Change'), ('COST_CHANGE', 'Cost Change'), ('CREATED', 'Created'), ('STOCK_TAKE', 'Stock Take'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('RETURN_OUT', 'Return Out'), ('STOCK_REVERSAL', 'Stock Reversal')], max_length=50),
        ),
    ]
