# Generated by Django 6.0.3 on 2026-03-16 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_carriageinward'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentpayment',
            name='cash_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installment_records', to='finance.cashtransaction'),
        ),
        migrations.AddField(
            model_name='sale',
            name='cash_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_records', to='finance.cashtransaction'),
        ),
    ]
