# Generated by Django 6.0.3 on 2026-03-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_installmentpayment_cash_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
