# Generated by Django 6.0.3 on 2026-03-18 22:48

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_profit_sale_total_cost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installmentpayment',
            options={'verbose_name_plural': 'Installment Payments'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name_plural': 'Sales'},
        ),
        migrations.AlterModelOptions(
            name='salecategory',
            options={'verbose_name_plural': 'Sale Categories'},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'verbose_name_plural': 'Sale Items'},
        ),
        migrations.AlterModelOptions(
            name='salesgoal',
            options={'verbose_name_plural': 'Sales Goals'},
        ),
        migrations.AlterField(
            model_name='installmentpayment',
            name='id',
            field=models.CharField(default=core.utils.gen_ip_id, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sale',
            name='id',
            field=models.CharField(default=core.utils.gen_sa_id, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salecategory',
            name='id',
            field=models.CharField(default=core.utils.gen_slc_id, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='id',
            field=models.CharField(default=core.utils.gen_si_id, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salesgoal',
            name='id',
            field=models.CharField(default=core.utils.gen_sg_id, max_length=30, primary_key=True, serialize=False),
        ),
    ]
