# Generated by Django 6.0.3 on 2026-03-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_sale_customer_name_sale_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesgoal',
            name='period_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
