# Generated by Django 6.0.3 on 2026-03-26 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_salesgoal_period_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='discount_type',
            field=models.CharField(default='percentage', max_length=20),
        ),
    ]
