# Generated by Django 6.0.3 on 2026-03-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_saleitem_discount_percentage_saleitem_discount_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
