# Generated by Django 6.0.3 on 2026-03-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_sale_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('UNPAID', 'Unpaid'), ('INSTALLMENT', 'Installment'), ('QUOTE', 'Quote')], default='PENDING', max_length=50),
        ),
    ]
