# Generated by Django 6.0.3 on 2026-04-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_salesreturn_salesreturnitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='quantity_returned',
            field=models.IntegerField(default=0),
        ),
    ]
