# Generated by Django 6.0.3 on 2026-05-05 19:41

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0010_agency_is_frozen_branchcounter_last_reset_month'),
        ('sales', '0012_saleitem_quantity_returned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleSource',
            fields=[
                ('id', models.CharField(default=core.utils.gen_sls_id, max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_sources', to='core_app.agency')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_sources', to='core_app.branch')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sale Sources',
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.salesource'),
        ),
    ]
