# Generated by Django 6.0.3 on 2026-03-18 22:48

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='id',
            field=models.CharField(default=core.utils.gen_cp_id, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.CharField(default=core.utils.gen_me_id, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='id',
            field=models.CharField(default=core.utils.gen_mt_id, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='whatsappsession',
            name='id',
            field=models.CharField(default=core.utils.gen_ws_id, max_length=30, primary_key=True, serialize=False),
        ),
    ]
