# Generated by Django 6.0.3 on 2026-03-27 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_alter_campaign_id_alter_message_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatsappsession',
            options={'verbose_name_plural': 'WhatsApp Sessions'},
        ),
    ]
