# Generated by Django 6.0.3 on 2026-03-18 22:48

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverification_deletionrequest_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletionrequest',
            name='id',
            field=models.CharField(default=core.utils.gen_dr_id, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='id',
            field=models.CharField(default=core.utils.gen_ev_id, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='id',
            field=models.CharField(default=core.utils.gen_pt_id, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='permission',
            name='id',
            field=models.CharField(default=core.utils.gen_pe_id, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.CharField(default=core.utils.gen_ro_id, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=core.utils.gen_us_id, max_length=30, primary_key=True, serialize=False),
        ),
    ]
