# Generated by Django 6.0.3 on 2026-03-19 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_remove_activityhistory_location_id_and_more'),
        ('users', '0003_alter_deletionrequest_id_alter_emailverification_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core_app.branch'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
