# Generated by Django 6.0.3 on 2026-04-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_branch_alter_user_user_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='pin_required',
            field=models.BooleanField(default=True, help_text='If False, users with this role can bypass PIN verification'),
        ),
    ]
