# Generated by Django 6.0.3 on 2026-04-13 10:21

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_alter_agency_subscription_status_and_more'),
        ('users', '0005_role_pin_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_system_role',
            field=models.BooleanField(default=False, help_text='If True, this role cannot be deleted via the UI'),
        ),
        migrations.AddField(
            model_name='user',
            name='primary_branch',
            field=models.ForeignKey(help_text='The main branch this user is assigned to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_users', to='core_app.branch'),
        ),
        migrations.CreateModel(
            name='BranchInvitation',
            fields=[
                ('id', models.CharField(default=core.utils.gen_bi_id, max_length=30, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='PENDING', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_invitations', to='core_app.agency')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core_app.branch')),
                ('inviter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('email', 'branch', 'status')},
            },
        ),
    ]
