# Generated by Django 6.0.3 on 2026-04-14 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_alter_agency_subscription_status_and_more'),
        ('users', '0006_role_is_system_role_user_primary_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core_app.agency'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('agency', 'name')},
        ),
        migrations.RemoveField(
            model_name='role',
            name='branch',
        ),
    ]
