# Generated by Django 6.0.3 on 2026-04-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_role_unique_together_role_agency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_frozen',
            field=models.BooleanField(default=False, help_text='If true, the user is blocked from all system access regardless of subscription.'),
        ),
    ]
